installType: upstream
rbacApiVersion: rbac.authorization.k8s.io
namespace: olm
catalog_namespace: olm
operator_namespace: operators
imagestream: false
writeStatusName: '""'
writePackageServerStatusName: ""
olm:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:e9de77ac5c08643202ad42a0311d15c98ffbfd8a1dc2eab4e9f2dcaeed7110ac
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
catalog:
  replicaCount: 1
  image:
    ref: quay.io/operator-framework/olm@sha256:e9de77ac5c08643202ad42a0311d15c98ffbfd8a1dc2eab4e9f2dcaeed7110ac
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080
package:
  replicaCount: 2
  image:
    ref: quay.io/operator-framework/olm@sha256:e9de77ac5c08643202ad42a0311d15c98ffbfd8a1dc2eab4e9f2dcaeed7110ac
    pullPolicy: Always
  service:
    internalPort: 5443
  securityContext:
    runAsUser: 1000
catalog_sources:
  - rh-operators
